# Generated by Django 6.0.5 on 2026-07-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='peca',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='peca',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='catalogo.fornecedor'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(upload_to='pecas/'),
        ),
    ]
