# Generated by Django 6.0.5 on 2026-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_categoria_ativo_categoria_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peca',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
