# Generated by Django 6.0.5 on 2026-09-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_categoria_excluido_em_fornecedor_excluido_em_and_more'),
        ('pedidos', '0001_initial'),
        ('usuarios', '0004_confirmar_email_usuarios_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='usuarios.usuario')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='catalogo.peca')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomendas_respondidas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'encomendas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
