# Generated by Django 6.0.5 on 2026-09-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_encomenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
