# Generated by Django 6.0.5 on 2026-09-02 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='encomenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_carrinho', to='pedidos.encomenda'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='encomenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='pedidos.encomenda'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('concluida', 'Concluída')], default='pendente', max_length=10),
        ),
    ]
