# Generated by Django 6.0.5 on 2026-09-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_itemcarrinho_encomenda_itempedido_encomenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('reservado', 'Reservado')], default='concluido', max_length=20),
        ),
    ]
