# Generated by Django 6.0.5 on 2026-09-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_habilitada', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'configuracao_sistema',
            },
        ),
    ]
