# Generated by Django 6.0.5 on 2026-07-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsu', models.AutoField(primary_key=True, serialize=False)),
                ('nomUsu', models.CharField(max_length=45)),
                ('emailUsu', models.EmailField(max_length=45, unique=True)),
                ('senUsu', models.CharField(max_length=255)),
                ('telUsu', models.CharField(max_length=20)),
                ('tipoUsu', models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionario'), ('adm', 'Administrador')], default='cliente', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
