# Generated by Django 6.0.5 on 2026-07-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pode_gerenciar_pecas',
            field=models.BooleanField(default=False),
        ),
    ]
