# Generated by Django 6.0.5 on 2026-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_pode_gerenciar_pecas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
