# Generated by Django 6.0.5 on 2026-07-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_pode_gerenciar_pecas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('excluir', 'Excluir')], max_length=10)),
                ('modelo', models.CharField(help_text='Ex: Peca, Categoria, Fornecedor, Usuario', max_length=50)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_atividade', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'log_atividades',
                'ordering': ['-criado_em'],
            },
        ),
    ]
